# Generated by Django 6.1 on 2026-08-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_skill_professionalprofile_availability_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='expiry_date',
        ),
        migrations.AddField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.CharField(blank=True),
        ),
    ]
